### ISSUE TITLE
Causing OctoPrint 1.8.0 to crash (server not starting)

### ISSUE THREAD

**Issue by IHateNameStealers** [LuckyX182/Filament_sensor_simplified#53]
After updating to the new 1.8.0 version of OctoPrint, OctoPrint's server does not startup anymore until I disable "Filament Sensor Simplified".

Not sure if it's only with my setup.

Anyone else having the same issue?

**Comment by TrueKillRob** [comment]
I have the same problem: after updating my OctoPrint from 1.7.3 to 1.8, it crashes with my Ender 7 setup. On my Ender 3 setup it runs fine.

**Comment by LuckyX182** [comment]
Tested 0.3.1 version of plugin on 1.8.0 OctoPrint with no issues. What version of plugin are you running? Can you provide octoprint.log file?

**Comment by der-knusprige** [comment]
having the same problem on 1.8.0, the server wont start with this plugin

log:

2022-05-22 21:02:55,544 - octoprint.startup - INFO - ******************************************************************************
2022-05-22 21:02:55,553 - octoprint.startup - INFO - Starting OctoPrint 1.8.0
2022-05-22 21:02:55,555 - octoprint.startup - INFO - ******************************************************************************
2022-05-22 21:02:59,016 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity changed from offline to online
2022-05-22 21:03:10,072 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2022-05-22 21:03:10,072 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 1.1.1.1:53 is working
2022-05-22 21:03:10,073 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2022-05-22 21:03:10,101 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2022-05-22 21:03:13,654 - octoprint.startup - INFO - Added settings overlay from plugin consolidate_temp_control
2022-05-22 21:03:13,655 - octoprint.plugin.core - INFO - Found 23 plugin(s) providing 23 mixin implementations, 49 hook handlers
2022-05-22 21:03:14,069 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2022-05-22 21:03:14,092 - octoprint.server - INFO - Intermediary server started
2022-05-22 21:03:14,145 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2022-05-22 21:03:14,227 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2022-05-22 21:03:14,237 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_SHOW (needs: "Need(method='role', value='plugin_action_command_notification_show')")
2022-05-22 21:03:14,238 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_CLEAR (needs: "Need(method='role', value='plugin_action_command_notification_clear')")
2022-05-22 21:03:14,239 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: "Need(method='role', value='plugin_action_command_prompt_interact')")
2022-05-22 21:03:14,240 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: "Need(method='role', value='plugin_announcements_read')")
2022-05-22 21:03:14,240 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: "Need(method='role', value='plugin_announcements_manage'), Need(method='role', value='plugin_announcements_read')")
2022-05-22 21:03:14,241 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: "Need(method='role', value='plugin_appkeys_admin')")
2022-05-22 21:03:14,241 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_GRANT (needs: "Need(method='role', value='plugin_appkeys_user')")
2022-05-22 21:03:14,242 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: "Need(method='role', value='plugin_backup_access')")
2022-05-22 21:03:14,244 - octoprint.server - INFO - Added new permission from plugin firmware_check: PLUGIN_FIRMWARE_CHECK_DISPLAY (needs: "Need(method='role', value='plugin_firmware_check_display')")
2022-05-22 21:03:14,247 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: "Need(method='role', value='plugin_logging_manage')")
2022-05-22 21:03:14,250 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: "Need(method='role', value='plugin_pi_support_check')")
2022-05-22 21:03:14,254 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_LIST (needs: "Need(method='role', value='plugin_pluginmanager_manage')")
2022-05-22 21:03:14,256 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: "Need(method='role', value='plugin_pluginmanager_manage')")
2022-05-22 21:03:14,260 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: "Need(method='role', value='plugin_pluginmanager_install'), Need(method='role', value='plugin_pluginmanager_manage')")
2022-05-22 21:03:14,262 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: "Need(method='role', value='plugin_softwareupdate_check')")
2022-05-22 21:03:14,264 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: "Need(method='role', value='plugin_softwareupdate_update')")
2022-05-22 21:03:14,269 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CONFIGURE (needs: "Need(method='role', value='plugin_softwareupdate_configure')")
2022-05-22 21:03:15,689 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python3 -m pip" as command to invoke pip
2022-05-22 21:03:16,870 - octoprint.util.pip - INFO - Version of pip is 20.3.3
2022-05-22 21:03:16,909 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2022-05-22 21:03:16,909 - octoprint.util.pip - INFO - ==> pip ok -> yes
2022-05-22 21:03:17,113 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2022-05-22 21:03:17,178 - octoprint.plugins.softwareupdate - INFO - Cleaned up -4 old update log entries
2022-05-22 21:03:17,178 - octoprint.plugins.softwareupdate - INFO - Loaded update log from disk
2022-05-22 21:03:17,742 - octoprint.plugin.core - INFO - Initialized 23 plugin implementation(s)
2022-05-22 21:03:17,828 - octoprint.plugin.core - INFO - 23 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/backup
|  Consolidate Temp Control (0.1.8) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_consolidate_temp_control
|  Core Wizard (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/corewizard
|  Discovery (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/errortracking
|  Event Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/eventmanager
|  Filament Sensor Simplified (0.3.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_filamentsensorsimplified
|  File Check (2021.2.23) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_file_check
|  Firmware Check (2021.10.11) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_firmware_check
|  GCode Viewer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/gcodeviewer
|  GPIO Control (1.0.8) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_gpiocontrol
|  Logging (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/logging
|  Octoslack (2.2.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_Octoslack
|  Pi Support Plugin (2022.3.28) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pluginmanager
|  Printoid Plugin (1.2.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_printoid
|  Software Update (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2022-05-22 21:03:17,875 - octoprint.environment - INFO - Detected environment is Python 3.7.3 under Linux (linux). Details:
|  hardware:
|    cores: 4
|    freq: 1000.0
|    ram: 382251008
|  os:
|    bits: 32
|    id: linux
|    platform: linux
|  plugins:
|    pi_support:
|      model: Raspberry Pi Zero 2 W Rev 1.0
|      octopi_version: 0.18.0
|      octopiuptodate_build: 0.18.0-1.8.0-20220517112637
|      throttle_state: '0x0'
|  python:
|    pip: 20.3.3
|    version: 3.7.3
|    virtualenv: /home/pi/oprint
2022-05-22 21:03:17,909 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2022-05-22 21:03:17,909 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2022-05-22 21:03:17,909 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-manifest.json...
2022-05-22 21:03:18,157 - octoprint.cli.server - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/pi/oprint/bin/octoprint", line 8, in <module>
    sys.exit(main())
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/__init__.py", line 936, in main
    octo(args=args, prog_name="octoprint", auto_envvar_prefix="OCTOPRINT")
  File "/home/pi/oprint/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/pi/oprint/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/oprint/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/oprint/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/cli/server.py", line 330, in serve_command
    disable_color=no_color,
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/cli/server.py", line 163, in run_server
    octoprint_server.run()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/__init__.py", line 637, in run
    self._setup_blueprints()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/__init__.py", line 1773, in _setup_blueprints
    ) = self._prepare_blueprint_plugins()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/__init__.py", line 1820, in _prepare_blueprint_plugins
    blueprint, prefix = self._prepare_blueprint_plugin(plugin)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/__init__.py", line 1871, in _prepare_blueprint_plugin
    blueprint = plugin.get_blueprint()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/types.py", line 1432, in get_blueprint
    f = getattr(self, member)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_filamentsensorsimplified/__init__.py", line 68, in setting_cmd_action
    return int(self._settings.get(["cmd_action"]))
ValueError: invalid literal for int() with base 10: 'opnative'

**Comment by TrueKillRob** [comment]
Hi,

I have exact the same error message?
If you need a complete new Log, I can generate one after my print is finished.
(I disabled your plug-in as a workaround)


"/home/pi/oprint/lib/python3.7/site-packages/octoprint_filamentsensorsimplified/**init**.py", line 68, in setting_cmd_action return int(self._settings.get(["cmd_action"])) ValueError: invalid literal for int() with base 10: 'opnative'

**Comment by LuckyX182** [comment]
That looks weird indeed. I used opnative as option in february when developing but it was changed to 0 and 1 values very quickly and didn't make it into released code. Can you try reinstalling the plugin along with deleting plugin data?

**Comment by TrueKillRob** [comment]
This was the solution!!!! Uninstall with Cleanup and reinstall :-)
I only have to reconfiugre it, but this is simple...

Only for your info. The Install-Log:

Installiere Plugin "Filament Sensor Simplified" von https://github.com/LuckyX182/Filament_sensor_simplified/archive/master.zip...
/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmpdl2yqgw4/Filament_sensor_simplified-master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpdl2yqgw4/Filament_sensor_simplified-master.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.7/site-packages (from Filament-sensor-simplified==0.3.1) (1.8.0)
Requirement already satisfied: RPi.GPIO in /home/pi/oprint/lib/python3.7/site-packages (from Filament-sensor-simplified==0.3.1) (0.7.0)
Requirement already satisfied: pathvalidate<3,>=2.4.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2.5.0)
Requirement already satisfied: colorlog<7,>=6 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (6.6.0)
Requirement already satisfied: unidecode in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (0.4.21)
Requirement already satisfied: Click<9,>=8.0.3 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (8.1.3)
Requirement already satisfied: Flask-Babel<3,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2.0.0)
Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2.8.5)
Requirement already satisfied: sarge==0.1.6 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (0.1.6)
Requirement already satisfied: flask<3,>=2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2.1.2)
Requirement already satisfied: watchdog<2,>=1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.0.2)
Requirement already satisfied: wrapt<1.14,>=1.13.3 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.13.3)
Requirement already satisfied: tornado<7,>=6.0.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (6.1)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (0.5.0)
Requirement already satisfied: zeroconf<0.34,>=0.33 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (0.33.4)
Requirement already satisfied: netaddr<0.9,>=0.8 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (0.8.0)
Requirement already satisfied: feedparser<7,>=6.0.8 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (6.0.8)
Requirement already satisfied: websocket-client<2,>=1.2.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.3.2)
Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2021.2.23)
Requirement already satisfied: markdown<4,>=3.2.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (3.3.7)
Requirement already satisfied: regex in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2020.11.13)
Requirement already satisfied: werkzeug<2.1,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2.0.3)
Requirement already satisfied: cachelib<0.3,>=0.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (0.2.0)
Requirement already satisfied: netifaces<1,>=0.11 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (0.11.0)
Requirement already satisfied: filetype<2,>=1.0.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.0.7)
Requirement already satisfied: future<1,>=0.18.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (0.18.2)
Requirement already satisfied: zipstream-ng<2.0.0,>=1.3.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.3.4)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.10.11 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2021.10.11)
Requirement already satisfied: frozendict<3,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2.3.2)
Requirement already satisfied: PyYAML<6,>=5.4.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (5.4.1)
Requirement already satisfied: pylru<2,>=1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.2.0)
Requirement already satisfied: blinker<2,>=1.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.4)
Requirement already satisfied: requests<3,>=2.26.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2.26.0)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2.0)
Requirement already satisfied: sentry-sdk<2,>=1.5.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.5.12)
Requirement already satisfied: emoji<2,>=1.4.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.6.1)
Requirement already satisfied: pkginfo<2,>=1.7.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (1.7.1)
Requirement already satisfied: pyserial<4,>=3.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (3.5)
Requirement already satisfied: OctoPrint-PiSupport>=2022.3.28 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (2022.3.28)
Requirement already satisfied: psutil<6,>=5.8 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Filament-sensor-simplified==0.3.1) (5.8.0)
Requirement already satisfied: importlib-metadata in /home/pi/oprint/lib/python3.7/site-packages (from Click<9,>=8.0.3->OctoPrint->Filament-sensor-simplified==0.3.1) (4.11.3)
Requirement already satisfied: sgmllib3k in /home/pi/oprint/lib/python3.7/site-packages (from feedparser<7,>=6.0.8->OctoPrint->Filament-sensor-simplified==0.3.1) (1.0.0)
Requirement already satisfied: itsdangerous>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from flask<3,>=2->OctoPrint->Filament-sensor-simplified==0.3.1) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in /home/pi/oprint/lib/python3.7/site-packages (from flask<3,>=2->OctoPrint->Filament-sensor-simplified==0.3.1) (3.1.2)
Requirement already satisfied: webassets>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->Filament-sensor-simplified==0.3.1) (2.0)
Requirement already satisfied: pytz in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<3,>=2.0->OctoPrint->Filament-sensor-simplified==0.3.1) (2020.5)
Requirement already satisfied: Babel>=2.3 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<3,>=2.0->OctoPrint->Filament-sensor-simplified==0.3.1) (2.9.0)
Requirement already satisfied: zipp>=0.5 in /home/pi/oprint/lib/python3.7/site-packages (from importlib-metadata->Click<9,>=8.0.3->OctoPrint->Filament-sensor-simplified==0.3.1) (3.8.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/pi/oprint/lib/python3.7/site-packages (from importlib-metadata->Click<9,>=8.0.3->OctoPrint->Filament-sensor-simplified==0.3.1) (4.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from Jinja2>=3.0->flask<3,>=2->OctoPrint->Filament-sensor-simplified==0.3.1) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->Filament-sensor-simplified==0.3.1) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->Filament-sensor-simplified==0.3.1) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->Filament-sensor-simplified==0.3.1) (2020.12.5)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->Filament-sensor-simplified==0.3.1) (2.0.7)
Requirement already satisfied: ifaddr>=0.1.7 in /home/pi/oprint/lib/python3.7/site-packages (from zeroconf<0.34,>=0.33->OctoPrint->Filament-sensor-simplified==0.3.1) (0.1.7)
Building wheels for collected packages: Filament-sensor-simplified
Building wheel for Filament-sensor-simplified (setup.py): started
Building wheel for Filament-sensor-simplified (setup.py): finished with status 'done'
Created wheel for Filament-sensor-simplified: filename=Filament_sensor_simplified-0.3.1-py3-none-any.whl size=15614 sha256=12a492f3efb36c86696fb33c4185f585aa545eaa7ed950320acb4eb1aa083b5f
Stored in directory: /tmp/pip-ephem-wheel-cache-atisk3c3/wheels/a1/93/7b/976bb5c34ff5f4876d353afad4ed2f48f180a8e559157d7f73
Successfully built Filament-sensor-simplified
Installing collected packages: Filament-sensor-simplified
Successfully installed Filament-sensor-simplified-0.3.1
Fertig!

**Comment by IHateNameStealers** [comment]
Doing a 3 day print at this moment (plugin was really needed this time).
When done, I will reinstall and try again.
Thank you for the info.
