### ISSUE TITLE
Running test says "trigger_mode is not defined" when it is

### ISSUE THREAD

**Issue by derekantrican** [LuckyX182/Filament_sensor_simplified#68]
Possibly related to #66 (default settings not working)

Screenshot:

![image](https://user-images.githubusercontent.com/1558019/210040011-94409912-21f1-4537-906a-79c85135e159.png)

octoprint.log:

```
2022-12-30 06:01:46,382 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin filamentsensorsimplified
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_filamentsensorsimplified/__init__.py", line 107, in on_api_command
    self._logger.info(f"Perfoming test (mode: {mode}, pin: {selected_pin}, triggered_mode: {trigger_mode}")
NameError: name 'trigger_mode' is not defined
```

It says "trigger_mode is not defined" but you can see from the screenshot that it is

**Comment by derekantrican** [comment]
Wait - nvm. This one is my fault (messing around with __init__.py)
